FROM python:3.8 as builder
WORKDIR /argus
COPY ./requirements.txt ./requirements.txt
RUN python -m venv /argus/venv  \
    && /argus/venv/bin/python -m pip install --upgrade pip \
    && /argus/venv/bin/python -m pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ \
    && apt update -y \
    && apt upgrade -y \
    && apt install -y tzdata


FROM python:3.8
ENV PYTHONUNBUFFERED=1
WORKDIR /argus
COPY . .
COPY --from=builder /argus/venv/ /argus/venv/
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN mkdir -p /argus/logs/startup

EXPOSE 7777

CMD ["sh", "-c", "exec /argus/venv/bin/gunicorn main:argus -b 0.0.0.0:7777 -w 8 -k uvicorn.workers.UvicornWorker --log-level info --access-logfile - --error-logfile - 2>&1 | tee -a /argus/logs/startup/argus-api.log"]
