FROM python:3.8 as builder
WORKDIR /argus
COPY ./requirements.txt ./requirements.txt
RUN python -m venv /argus/venv  \
    && /argus/venv/bin/python -m pip install --upgrade pip \
    && /argus/venv/bin/python -m pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ \
    && apt update -y \
    && apt upgrade -y \
    && apt install -y tzdata \
    && apt install -y wget \
    && wget https://github.com/vishnubob/wait-for-it/raw/master/wait-for-it.sh


FROM python:3.8
ENV PYTHONUNBUFFERED=1
WORKDIR /argus
COPY . .
COPY --from=builder /argus/venv/ /argus/venv/
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY --from=builder /argus/wait-for-it.sh /argus/ops/wait-for-it.sh
RUN ln -sf /argus/ops/dev.env.ops /argus/conf/dev.env \
    && chmod +x /argus/ops/wait-for-it.sh

EXPOSE 7777

CMD ["/argus/venv/bin/supervisord", "-c", "/argus/ops/supervisor.conf"]
