version: "3.3"

services:
  argus-mysql:
    image: mysql:8.0
    container_name: argus_mysql
    restart: always
    env_file:
      - ../conf/pro.env
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    environment:
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - argus_backend

  argus-redis:
    image: redis:7-alpine
    container_name: argus_redis
    restart: always
    env_file:
      - ../conf/pro.env
    command: >
      sh -c 'if [ -n "$$REDIS_PASSWORD" ]; then
      exec redis-server --appendonly yes --requirepass "$$REDIS_PASSWORD";
      else
      exec redis-server --appendonly yes;
      fi'
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - argus_backend

  argus-rabbitmq:
    image: rabbitmq:3-management
    container_name: argus_rabbitmq
    restart: always
    env_file:
      - ../conf/pro.env
    environment:
      TZ: Asia/Shanghai
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - argus_backend

  argus-rustfs:
    image: rustfs/rustfs:latest
    container_name: argus_rustfs
    user: "0:0"
    env_file:
      - ../conf/pro.env
    ports:
      - "9000:9000"
      - "9091:9001"
    volumes:
      - ./data:/data
      - ./logs:/logs
    networks:
      - argus_backend
    restart: unless-stopped

  argus-api:
    build:
      context: ../
      dockerfile: ops/dockerfile
      args:
        buildno: 1
    container_name: argus_api
    restart: always
    depends_on:
      - argus-mysql
      - argus-redis
      - argus-rabbitmq
      - argus-rustfs
    ports:
      - "7777:7777"
    env_file:
      - ../conf/pro.env
    environment:
      TZ: Asia/Shanghai
      argus_env: pro
    volumes:
      - ../logs:/argus/logs
      - ../ui_runner:/argus/ui_runner
    networks:
      - argus_backend

  argus-ui-runner:
    build:
      context: ../ui_runner
      dockerfile: Dockerfile
    container_name: argus_ui_runner
    restart: always
    depends_on:
      - argus-api
    env_file:
      - ../ui_runner/.env
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ../ui_runner:/app
      - ui_runner_node_modules:/app/node_modules
      - ../logs:/app/logs
    networks:
      - argus_backend

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
  ui_runner_node_modules:

networks:
  argus_backend:
