server {
  listen 80;
  server_name _;

  location /statics/ {
    alias /pity/statics/;
    autoindex off;
    expires 7d;
    add_header Cache-Control "public, max-age=604800";
  }

  location / {
    proxy_pass http://pity_server:7777;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
